package it.polimi.ingsw.network.message;

/**
 * Carries the exception message generated by an illegal move.
 * @author Mattia Lucamarini
 */
public class IllegalMove extends Message {
    String reason;

    /**
     * @param reason exception message
     */
    public IllegalMove(String reason){
        super(MessageCode.MOVE_ILLEGAL);
        this.reason = reason;
    }
    public String getReason() {
        return reason;
    }
}
