package it.polimi.ingsw.network.message;

import java.util.ArrayList;

/**
 * Contains the player order generated by the server.
 * @author Mattia Lucamarini
 */
public class PlayerOrder extends Message {
    private ArrayList<String> order;

    /**
     * @param order ordered list of usernames
     */
    public PlayerOrder(ArrayList<String> order){
        super(MessageCode.PLAYER_ORDER);
        this.order = order;
    }

    public ArrayList<String> getOrder() {
        return order;
    }
}
